WithUS-ZB/withme-fe

- src/App.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/index.css
- src/pages/Home.tsx
- tailwind.config.js
- 웹 : 본문 : 1200px / 모바일 : 360px
- Header : 스타일 및 레이아웃 변경
> Style : 화면크기 구성 및 Header 수정

- src/App.tsx
- src/pages/Login.tsx
-footer 페이지 하단 고정을위한 outlet 최소크기 지정
> Style : outlet 최소 크기 설정

- package.json
- src/App.css
- src/App.tsx
- src/components/Carousel.tsx
- src/components/InfoCarousel.tsx
- src/index.css
- src/pages/Home.tsx
- src/pages/Login.tsx
- yarn.lock
- 다크모드시 main 외에 색상 변경되지 않는 부분 수정
- 캐러셀 추가
- CSS 커스텀 부분 수정
> Home 레이아웃 작업 및 다크모드 설정

- src/components/Carousel.tsx
- src/components/InfoCarousel.tsx
> Style : 캐러셀 반응형 수정

- package.json
- src/pages/Join.tsx
- src/pages/Login.tsx
- yarn.lock
- 회원가입페이지 레이아웃 완료
- react-hook-form 입력값 관리
- 로그인 페이지 react-hook-form 입력값 관리
- 백엔드 API 대기중
> Feat : 회원가입페이지 레이아웃 및 통신 준비 완료

- src/components/Carousel.tsx
- src/components/InfoCarousel.tsx
> Style : 홈 스타일 수정

- package.json
- public/mockServiceWorker.js
- src/components/Header.tsx
- src/main.tsx
- src/mocks/browser.tsx
- src/mocks/handlers.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/pages/Mypage.tsx
- src/store/store.tsx
- yarn.lock
-로그인시 msw 사용하여 모의 데이터를 이용해 유저 정보 받아오는거 확인
-refresh 토큰 및 로그인시 회원가입 페이지 로그인 페이지 접근 제한 추가 필요.
> Feat : 로그인 msw 이용하여 모의 데이터 추가

- src/components/Header.tsx
- src/components/ScrollUpBtn.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- 반응형, 다크모드, 디자인 개선
- 스크롤업 버튼 추가 배치
> Style, Feat : 헤더, 로그인, 회원가입 디자인 및 다크모드 개선, 스크롤업 버튼 추가

- src/components/PostCard.tsx
- src/components/SearchBar.tsx
- src/pages/Event.tsx
- src/pages/Write.tsx
- tailwind.config.js
- 리스트 페이지 레이아웃 작성 
- 검색창 컴포넌트 추가
- 아이템카드 컴포넌트 추가
- main branch 에서 작업 -> git cherry-pick 으로 해결시도
> Style : 리스트 페이지 레이아웃, 검색창 & 아이템카드 컴포넌트 작업

- src/main.tsx
- src/routes/protectedRoute.tsx
- src/routes/routing.tsx
- 로그인 인증에 따른 페이지 접근 제한
- router 폴더생성하여 router 관리
> Refactor : router 구조 변경 및 페이지 로그인 인증

- src/routes/protectedRoute.tsx
> Fix : 문구 오타 수정

- index.html
- src/components/Header.tsx
- src/components/PostCard.tsx
- src/pages/MyManage.tsx
- src/pages/modal/AppStatusModal.tsx
- src/pages/modal/Modal.tsx
- src/pages/modal/PaymentModal.tsx
- src/pages/modal/SubscribeModal.tsx
- ReactDOM의 Protal을 사용하여 modal 구현
- pages 폴더안의 modal 폴더 만들어서 modal page 관리
- modal을 랜더링 해줄 대표적인 Modal 페이지 만든 후 그리고 싶은 modal page를 props로 받아오기
- modal page style은 각 기능 별 branch에서 작업 바람
> Feat : Modal 기초 설정 추가

- src/pages/Event.tsx
- src/pages/Home.tsx
- Event 파일과 Home 파일의 경로 오류로 인한 에러 수정
> Fix : 파일 경로 수정

- src/pages/modal/Modal.tsx
> Feat : modal 이벤트 전파 방지 로직 추가

- src/components/common/Header.tsx
- src/components/post/PostCard.tsx
- src/pages/Event.tsx
- src/pages/Home.tsx
- src/pages/MyManage.tsx
- src/pages/Write.tsx
- src/pages/modal/AppStatusModal.tsx
- src/pages/modal/Modal.tsx
- 기존 레이아웃에서 사이트 스타일에 맞게 변경
- 비사용 태그 하나 삭제 ( 포스트 카드 )
> Style : 내 모임관리 스타일 변경

- src/pages/Join.tsx
- src/pages/Login.tsx
- 백엔드와 로그인 기능 통신으로 엑세스 토큰으로 회원 정보 받기  확인
- 이메일 중복체크 기능 추가
- 소셜로그인 기본적인 부분 추가
> Feat : 로그인 백엔드 통신 구현 및 회원가입 이메일 중복체크 기능 추가

- src/Hooks/useGetPost.ts
- src/components/common/Header.tsx
- src/components/post/PostCard.tsx
- src/pages/Post.tsx
- Main, Event 따로 페이지로 조회하는 부분 삭제 후 Post 페이지로 통합 ( 같은 통신, 레이아웃 구조 해결 )
- 서버 통신으로 게시글 목록 데이터 조회 성공
- 커스텀 훅 생성하여 데이터 가공
> Feat : 게시글 조회페이지 변경, 통신 코드 작성 ( 작성된 게시글 목록 불러오기 )

- src/pages/Join.tsx
- 이메일 중복확인을 누르지 않아도 이메일 중복확인 벨리데이션이 보이는 오류 수정
> Fix : 이메일 중복확인 버튼 버그 수정

- src/Hooks/useComment.ts
- src/Hooks/useGetPost.ts
- src/Hooks/useWrite.ts
- src/components/detail/CommentBar.tsx
- src/components/home/Banner.tsx
- src/components/post/PostCard.tsx
- src/components/post/SearchBar.tsx
- src/pages/Post.tsx
- src/pages/PostDetail.tsx
- 게시글 작성 통신 보완 ( 통신요청시 누락된 항목 수정 )
- 게시글 조회 통신 ( 리스트 형태, 누락된 항목 수정 )
- 디테일 페이지 레이아웃, 통신 기능 구현
- 디테일 댓글 컴포넌트 작성 및 데이터 통신 ( 조회, 작성 ), 수정, 삭제 추가 구현 예정
> Feat : 게시글 작성, 게시글 조회, 디테일 페이지, 디테일 댓글

- src/pages/Mypage.tsx
- src/pages/modal/PhoneCertificationModal.tsx
- 마이페이지 닉네임 중복확인 기능 로직 추가
- 마이페이지 휴대폰 인증 기능추가(미완성)
- 모달 폴더에 휴대폰 인증 모달 추가
> Feat : 마이페이지 닉네임 중복확인 및 휴대폰 인증 추가

- src/routes/protectedRoute.tsx
- protectedrouter에서 로그인 알림을 alert에서 모달로 변경
> Style : 로그인 알림 모달 추가

- src/components/common/Header.tsx
> Fix : 헤더의 모임 관리 router 설정

- src/Hooks/useComment.ts
- src/Hooks/useParticipation.ts
- src/components/detail/CommentBar.tsx
- src/components/post/PostCard.tsx
- src/components/post/SearchBar.tsx
- src/pages/PostDetail.tsx
- src/routes/routing.tsx
- 게시글 댓글 수정, 삭제
- 모임 참여 통신 확인
- 자신이 쓴 댓글이 아닐 경우 수정, 삭제 불가
- 모임관리 테스트코드
- 추후 변경 사항 : 댓글 누락 데이터 ( 작성자 아이디, 이미지 ) 수정되면 수정할 예정 ( 프로필 페이지 이동, 테스트코드 삭제 )
> Feat : 게시글 댓글 실시간 추가, 등록, 삭제, 모임 참여 통신

- src/pages/PostDetail.tsx
- src/pages/UserPage.tsx
> Fix : 레거시 코드 삭제

- src/Hooks/useWrite.ts
- src/components/post/PostCard.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/pages/PostDetail.tsx
- src/pages/Write.tsx
- useWirte 훅에 goEdit 함수 추가
- 상태 변경 적용안됨 ( 고치는 중 )
> Feat : 게시글 수정 기능 구현 중

- src/pages/Login.tsx
- src/pages/ParsingToken.tsx
- src/pages/RequiredInfo.tsx
- src/routes/routing.tsx
- 카카오 로그인 시 리다이렉션 페이지 추가
- 카카오 회원가입 성공 시 필수정보 입력 페이지 추가
> Feat : 카카오 소셜 로그인 기능 추가

- src/pages/ParsingToken.tsx
- src/pages/RequiredInfo.tsx
- src/pages/UserPage.tsx
- src/pages/Write.tsx
- src/routes/routing.tsx
- 페이지 이동 에러 확인 후 수정 ( userPage.tsx ) - 구 포스트카드 사용
> Fix : UserPage 라우팅 에러 수정

- src/Hooks/useComment.ts
- src/Hooks/useGetPost.ts
- src/Hooks/useWrite.ts
- src/main.tsx
- src/pages/Post.tsx
- src/pages/Write.tsx
- React-Query 도입
- 이미지 파일 서버 보내기
> Fix : 게시글 데이터 React-Query 변경, 이미지 파일업로드 준비

- src/Hooks/useWrite.ts
- src/components/home/InfoCarousel.tsx
- src/components/post/PostCard.tsx
- src/pages/Home.tsx
- src/pages/PostDetail.tsx
- src/pages/Write.tsx
- 축제 불러오기 API 통신 성공
- 불러온 데이터 컴포넌트에 적용
> Feat : 축제 정보 통신 연동

- src/pages/Mypage.tsx
> Feat : 프로필 이미지 변경 기능 추가

- src/pages/Home.tsx
> Fix : vercel 배포 문제로 인한 수정

- src/Hooks/useWrite.ts
- src/components/detail/CommentBar.tsx
- src/pages/Mypage.tsx
- src/pages/PostDetail.tsx
- src/pages/Write.tsx
- src/routes/protectedRoute.tsx
> Style : 마이페이지 스타일 변경

- src/Hooks/useGetPost.ts
- src/Hooks/useWrite.ts
- src/components/common/Header.tsx
- src/main.tsx
- src/pages/Post.tsx
- src/pages/Write.tsx
- src/routes/routing.tsx
> Fix : 게시글 작성 이미지 연동

- src/main.tsx
- src/pages/PostDetail.tsx
> Fix : 참여 상태 업데이트 테스트 중

- src/pages/PostDetail.tsx
> Fix : main -> gathering

- src/Hooks/useWrite.ts
- src/components/post/SearchBar.tsx
- navigate 수정
- git pull conflict 해결
> Fix : 게시글 작성 후 수정 전 페이지로 보내는 로직 수정

- public/mockServiceWorker.js
- src/Hooks/useGetPost.ts
- src/Hooks/useLikes.ts
- src/components/detail/CommentBar.tsx
- src/components/home/Carousel.tsx
- src/components/mypage/ListCard.tsx
- src/components/post/PostCard.tsx
- src/main.tsx
- src/pages/Home.tsx
- src/pages/Mypage.tsx
- src/pages/PostDetail.tsx
- 실제 서버 데이터에서 인기순 받아와 캐러셀 띄우기
- 마이페이지, 리스트 카드 레이아웃 변경
> Feat : 홈 캐러셀 데이터 ( 인기순 ) 데이터 통신, 마이페이지, 리스트카드 컴포넌트 스타일 변경

- src/Hooks/useGathering.ts
- src/Hooks/useGetPost.ts
- src/Hooks/useParticipation.ts
- src/Hooks/useWrite.ts
- src/api/axiosConfig.ts
- src/components/common/Header.tsx
- src/components/home/Carousel.tsx
- src/components/mymanage/AppList.tsx
- src/components/mymanage/GatheringCard.tsx
- src/components/post/PostCard.tsx
- src/components/post/SearchBar.tsx
- src/main.tsx
- src/pages/Chat.tsx
- src/pages/Home.tsx
- src/pages/MyManage.tsx
- src/pages/Mypage.tsx
- src/pages/PostDetail.tsx
- src/pages/Write.tsx
- src/pages/modal/AppStatusModal.tsx
- src/pages/modal/Modal.tsx
- src/routes/routing.tsx
- src/store/postStore.ts
- src/store/userStore.ts
- tailwind.config.js
- 모임 개설 관련 통신 ( 참가, 취소, 수락, 거절 )
- 이미지 수정 오류 고침
- 반응형 수정
> Feat : 모임관리 통신, 반응형 수정

- src/Hooks/useGetPost.ts
- src/pages/Post.tsx
- src/pages/PostDetail.tsx
- 10개씩 페이지네이션으로 카드 보여주기
- 검색 후 [ 전체 ] [ 이벤트 ] [ 모임 ] 클릭시 리랜더링 되지 않는 부분 수정
> Feat : 포스트 페이지네이션, 검색 후 데이터 불러오기 오류 수정

- index.html
- src/Hooks/useGetPost.ts
- src/Hooks/usePayment.ts
- src/components/detail/CommentBar.tsx
- src/pages/Mypage.tsx
- src/pages/Post.tsx
- src/pages/PostDetail.tsx
- src/pages/Write.tsx
- src/pages/modal/AlarmModal.tsx
- src/pages/modal/PaymentModal.tsx
- KCP 활용 결제 시스템 추가 ( 서버 연동 )
- 반응형 수정
> Feat : 결제 시스템 추가 구현

- src/Hooks/useGetPost.ts
- src/pages/Mypage.tsx
- src/pages/Post.tsx
> Fix : Post 페이지 검색 후 카테고리 변경시 리랜더링 실패 수정

- package.json
- src/components/common/Header.tsx
- src/components/mymanage/GatheringCard.tsx
- src/pages/Chat.tsx
- src/pages/Mypage.tsx
- src/routes/routing.tsx
- vite.config.ts
- yarn.lock
- 내 모임관리 페이지에서 채팅방 개설
- 마이페이지 채팅방 목록 추가
- chat 웹 소켓 연결 로직 (미완성)
- conflict 해결
> Feat : 채팅방 개설 , 마이페이지 채팅방 목록 추가

- src/Hooks/useGetPost.ts
- src/pages/Post.tsx
- 서버에서 데이터 10 단위로 더 받아오는 버튼 구현
> Feat : 더보기 버튼 생성

- src/components/common/Footer.tsx
- src/components/mymanage/AppList.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
> Style : footer 변경
